//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inicioRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int idCuenta { get; set; }
        public string numCuenta { get; set; }
        public double saldo { get; set; }
        public int fk_idCliente { get; set; }
    }
}
