//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inicioRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        public int idSolicitud { get; set; }
        public double montoSolicitado { get; set; }
        public string fechaSolicitud { get; set; }
        public string estadoSolicitud { get; set; }
        public int fk_idCliente { get; set; }
        public string numCuenta { get; set; }
    }
}
