//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inicioRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanSchedule
    {
        public int idCronograma_pres { get; set; }
        public int fk_idPrestamo { get; set; }
        public double cuotaPrestamo { get; set; }
        public string tipoPago { get; set; }
        public double abonoCapital { get; set; }
        public string fechaPlanificada { get; set; }
        public string fechaEfectiva { get; set; }
        public int fk_idComprobante { get; set; }
        public int fk_idCliente { get; set; }
    }
}
